### ISSUE TITLE
Unicode input with two or more cursors

### ISSUE THREAD

**Issue by jonaprieto** [banacorn/language-agda#13]
I use to replace text using ctrl+D to select the same matches for example.
But with the cursors that the atom puts, when I try to write some Unicode character,
what I got is that only in the last line (last match) the Unicode appears. Why?

For example, 
```
A
...
A
```

After selecting the As with two cursors (symbol |)

```
A|
...
A|
```

And if I try to type `\_1` instead of 

```
A₁
...
A₁
```
This is what I got
```
A₁
...
A_1
```

**Comment by banacorn** [comment]
Because it never came to me that that we can type unicode symbols simultaneously at different places XD

Did some quick survey, here's the [problem](https://github.com/banacorn/agda-mode/blob/master/src/input-method.ts#L255):

```typescript
const selectedRange = this.editor.getSelectedBufferRange();
```

Here's the [solution](https://atom.io/docs/api/v1.28.1/TextEditor#instance-getSelectedBufferRanges)!:

```typescript
const selectedRange = this.editor.getSelectedBufferRanges();
```
